name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "huynhviet"
          entrypoint: "main.ts"
          root: ""

  purge-cache:
    needs: deploy
    name: Purge cache
    uses: ./.github/workflows/purge-cache.yml
    secrets: inherit
