name: Test

on:
  push:
    branches:
      - renovate/**
  workflow_call:

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Test step
        run: "deno task test"
